# Generated by Django 6.0.5 on 2026-05-11 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'goal_type'], name='goals_goal_user_id_136a72_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['start_date', 'end_date'], name='goals_goal_start_d_825b5c_idx'),
        ),
    ]
