# Generated by Django 6.0.5 on 2026-05-11 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_log', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='foodlog',
            index=models.Index(fields=['user', 'date'], name='food_log_fo_user_id_e4c178_idx'),
        ),
        migrations.AddIndex(
            model_name='foodlog',
            index=models.Index(fields=['meal_type'], name='food_log_fo_meal_ty_e79af8_idx'),
        ),
    ]
